sudo: required
services:
  - docker

before_install:
  - docker build -t ddzmitry/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run ddzmitry/react-test npm test -- --coverage

# Build all images
after_success:
  - docker build -t ddzmitry/multi-client:latest -f ./client
  - docker build -t ddzmitry/multi-nginx:latest   -f ./nginx
  - docker build -t ddzmitry/multi-server:latest  -f ./server
  - docker build -t ddzmitry/multi-worker:latest  -f ./worker 
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take images and Push all to DockerHub
  - docker push ddzmitry/multi-client:latest 
  - docker push ddzmitry/multi-nginx:latest 
  - docker push ddzmitry/multi-server:latest 
  - docker push ddzmitry/multi-worker:latest 